### ISSUE TITLE
Project MMO (pmmo) has failed to load correctly (1.16.5 server)

### ISSUE THREAD

**Issue by Xodi21** [Caltinor/Project-MMO-2.0#186]
[modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: pmmo, class harmonised.pmmo.ProjectMMOMod
java.lang.IncompatibleClassChangeError: Method 'dev.ftb.mods.ftbquests.quest.task.TaskType dev.ftb.mods.ftbquests.quest.task.TaskTypes.register(net.minecraft.util.ResourceLocation, dev.ftb.mods.ftbquests.quest.task.TaskType$Provider, java.util.function.Supplier)' must be InterfaceMethodref constant
        at harmonised.pmmo.ftb_quests.FTBQHandler.<clinit>(FTBQHandler.java:13) ~[pmmo:1.16.5-3.67.6] {re:classloading}
        at harmonised.pmmo.ProjectMMOMod.<init>(ProjectMMOMod.java:62) ~[pmmo:1.16.5-3.67.6] {re:classloading}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?] {re:classloading}
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {re:classloading}
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?] {}
        at java.lang.Class.newInstance(Class.java:584) ~[?:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.2] {re:classloading}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) [?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) [?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?] {re:computing_frames}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?] {re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?] {}

------------------------------------------------

        Crash Report UUID: 50055f2e-1cdb-425d-993a-272dbd5852f0[08:20:03] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Project MMO (pmmo) has failed to load correctly
§7java.lang.IncompatibleClassChangeError: Method 'dev.ftb.mods.ftbquests.quest.task.TaskType dev.ftb.mods.ftbquests.quest.task.TaskTypes.register(net.minecraft.util.ResourceLocation, dev.ftb.mods.ftbquests.quest.task.TaskType$Provider, java.util.function.Supplier)' must be InterfaceMethodref constant
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:269) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:236) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:194) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[server.jar:36.2] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [server.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [server.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [server.jar:?] {}

**Screenshots**
![image](https://user-images.githubusercontent.com/123058679/213380488-7815795d-0a32-4867-a835-6c80b54d5468.png)

![image](https://user-images.githubusercontent.com/123058679/213380587-fe2884dd-0ea7-4079-ae32-0d779cd07f61.png)

**Versions:**
 - Minecraft: 1.16.5
 - Loader: forge-1.16.5-36.2.33
 - PMMO: Project_MMO-1.16.5-3.67.6

**Comment by rxvse** [comment]
same issue here, have you found any solution yet?

**Comment by rxvse** [comment]
I've checked closed threads and someone said to just get beta version of FTBquests mod, but it didn't work for me

**Comment by rxvse** [comment]
After trying alot things, I just changed Java version to 8 and it worked for me.

**Comment by Caltinor** [comment]
Java 8 is required for 1.16 and below. 1.17 uses java 16 and 1.18 uses java 17.
