### ISSUE TITLE
mmo

### ISSUE THREAD

**Issue by robtbs** [Caltinor/Project-MMO-2.0#220]
---- Minecraft Crash Report ----
// My bad.

Time: 2/27/23 6:13 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.nbt.StringNBT.func_229705_a_(StringNBT.java:40) ~[?:?] {re:classloading}
	at net.minecraft.nbt.CompoundNBT.func_74778_a(CompoundNBT.java:150) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:CompoundNBTMixin,pl:mixin:A}
	at harmonised.pmmo.pmmo_saved_data.PmmoSavedData.func_189551_b(PmmoSavedData.java:113) ~[pmmo:1.16.5-3.68.0] {re:classloading}

minecraft 1.16.5
Project_MMO-1.16.5-3.68.0.jar

the server keeps crashing, not sure why

**Comment by SomewhatDamaged** [comment]
Please post/link to the full crash log and also list:

 - Loader: (eg. Forge-40.1.20)

**Comment by Caltinor** [comment]
I suspect they aren't uploading the log because it contains information they don't want public.  The obfuscated method names is sus.  We can reopen this if an actual crash log is uploaded.
