### ISSUE TITLE
Entity Type Null crash when using glossary

### ISSUE THREAD

**Issue by Turk645** [Caltinor/Project-MMO-2.0#351]
**Description**
untamedwilds.entity.mammal.EntityBaleenWhale seems to be causing a crash. Something about it being a multi part entity is causing an issue it seems. Not sure if a try and catch would be a good solution or not to skip the entity render if an exception pops up

```
java.lang.NullPointerException: Cannot invoke "untamedwilds.util.EntityDataHolder.getScale(int)" because the return value of "untamedwilds.entity.ComplexMob.getEntityData(net.minecraft.world.entity.EntityType)" is null
	at untamedwilds.entity.ComplexMob.getModelScale(ComplexMob.java:195) ~[untamedwilds-1.19.2-3.0.2.jar%23623!/:1.19.2] {re:classloading}
	at untamedwilds.entity.mammal.EntityBaleenWhale.getMultiparts(EntityBaleenWhale.java:260) ~[untamedwilds-1.19.2-3.0.2.jar%23623!/:1.19.2] {re:classloading}
	at untamedwilds.entity.mammal.EntityBaleenWhale.<init>(EntityBaleenWhale.java:53) ~[untamedwilds-1.19.2-3.0.2.jar%23623!/:1.19.2] {re:classloading}
	at net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:469) ~[client-1.19.2-20220805.130853-srg.jar%23641!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.mixins.json:EntityTypeMixin,pl:mixin:APP:architectury-common.mixins.json:inject.MixinEntityType,pl:mixin:A}
	at harmonised.pmmo.client.gui.component.StatScrollWidget.lambda$generateGlossary$6(StatScrollWidget.java:235) ~[pmmo-1.19.2-3.2.4.jar%23567!/:1.19.2-3.2.4] {re:classloading}
```

**Versions:**
 - Minecraft: (eg 1.19.2)

**Comment by Caltinor** [comment]
This issue is on Untamed Wilds and is not exclusive to PMMO.  https://github.com/RayTrace082/untamedwilds/issues/251
