### ISSUE TITLE
MC 1.20.1 lockup issue

### ISSUE THREAD

**Issue by thepriz** [Caltinor/Project-MMO-2.0#484]
**Describe the bug**
Walking around and exploring the overworld the game locks up. The log files may indicate pmmo is a problem.

**Expected behavior**
Walk around and explore without the game locking up

**To Reproduce**
1. Walk around the world
2. Game locks up

**Screenshots**

**Versions:**
 - Minecraft: 1.20.1
 - Loader: Forge-47.2.20)
 - PMMO: 1.20.1-1.2.19

**Additional context**
[latest.log](https://github.com/Caltinor/Project-MMO-2.0/files/14474521/latest.log)

**Comment by Caltinor** [comment]
Two things.  
1. nothing in this log mentions pmmo as throwing an error
2. Forge added breaking changes in 47.2.x  I would roll back as far as you can to get out of the .2. range.  Preferably 47.1.3 since mods that work on that version are compatible between Forge and NeoForge.

**Comment by thepriz** [comment]
The latest log must of got archived. Here is the relivant error

[12:09:09] [Worker-Main-65/ERROR]: Async chunk load took way too long, this needs to be reported to the appropriate mod.
java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.handler$zck000$bailIfServerDead(ServerChunkCache.java:2622) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.world.level.Level.m_6522_(Level.java:187) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.world.level.LevelReader.m_46819_(LevelReader.java:129) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.world.level.Level.m_6325_(Level.java:182) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.world.level.Level.m_8055_(Level.java:355) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.world.level.LevelReader.m_46859_(LevelReader.java:85) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.world.entity.monster.Spider.getAdjustedOnPosition(Spider.java:1604) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.world.entity.Entity.handler$dim000$onGetOnPosition(Entity.java:14117) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.world.entity.Entity.m_20097_(Entity.java:815) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	**at harmonised.pmmo.features.mobscaling.MobAttributeHandler.handle(MobAttributeHandler.java:76) ~[pmmo-1.20.1-1.2.19.jar%231095!/:1.20.1-1.2.19]
	at harmonised.pmmo.features.mobscaling.MobAttributeHandler.onMobSpawn(MobAttributeHandler.java:61) ~[pmmo-1.20.1-1.2.19.jar%231095!/:1.20.1-1.2.19]
	at harmonised.pmmo.features.mobscaling.__MobAttributeHandler_onMobSpawn_FinalizeSpawn.invoke(.dynamic) ~[pmmo-1.20.1-1.2.19.jar%231095!/:1.20.1-1.2.19]**
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onFinalizeSpawn(ForgeEventFactory.java:281) ~[forge-1.20.1-47.2.20-universal.jar%231267!/:?]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.lambda$addEntitiesToWorld$5(StructureTemplate.java:432) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.addEntitiesToWorld(StructureTemplate.java:427) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.m_230328_(StructureTemplate.java:337) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.world.level.levelgen.structure.pools.SinglePoolElement.m_213695_(SinglePoolElement.java:124) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.m_226509_(PoolElementStructurePiece.java:89) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.m_213694_(PoolElementStructurePiece.java:85) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.world.level.levelgen.structure.StructureStart.m_226850_(StructureStart.java:90) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.m_223080_(ChunkGenerator.java:320) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar%23109!/:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(ChunkGenerator.java:319) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_279978_(ChunkStatus.java:108) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_214024_(ChunkStatus.java:309) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_280308_(ChunkStatus.java:252) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:643) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar%23114!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$29(ChunkMap.java:634) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[12:09:49] [ModernFix integrated server watchdog/ERROR]: A single server tick has taken 40001, more than 40000 milliseconds
[12:09:53] [ModernFix integrated server watchdog/ERROR]: Thread Dump:
"Render thread" prio=10 Id=1 RUNNABLE
	at MC-BOOTSTRAP/org.lwjgl.opengl@3.3.1+7/org.lwjgl.opengl.GL32C.nglClientWaitSync(Native Method)
	at MC-BOOTSTRAP/org.lwjgl.opengl@3.3.1+7/org.lwjgl.opengl.GL32C.glClientWaitSync(GL32C.java:718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.handler$bah000$preRender(Minecraft.java:18477)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
	at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.8/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.8/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler$$Lambda$1188/0x000000008067f948.run(Unknown Source)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at app/cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

**Comment by thepriz** [comment]
[2024-03-03-6.log.gz](https://github.com/Caltinor/Project-MMO-2.0/files/14475897/2024-03-03-6.log.gz)

**Comment by Caltinor** [comment]
okay, so the error is that the structure took too long too long to load.  Could you run a spark profile on this so we can see where in this stackttrace the delay is happening?

**Comment by thepriz** [comment]
Ok, will try an capture the issue with Spark

**Comment by Caltinor** [comment]
Another user was having a similar issue and found it resolved when they disabled Levelup Unlocks in pmmo-client.toml.  you might try that and see if your issue resolves.
