### ISSUE TITLE
Chat Error

### ISSUE THREAD

**Issue by Shadowyjp** [Caltinor/Project-MMO-2.0#521]
```
[00:14:12] [Server thread/ERROR]: Exception caught during firing event: Cannot invoke "java.util.List.stream()" because the return value of "java.util.Map.get(Object)" is null
Index: 1
Listeners:
0: NORMAL
1: ASM: class harmonised.pmmo.core.perks.FeaturePerks saveAttributesOnDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
2: ASM: class io.redspace.ironsspellbooks.player.ServerPlayerEvents onLivingDeathEvent(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
3: LOW
4: ASM: dev.shadowsoffire.apotheosis.adventure.AdventureEvents@4b028285 deathMark(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
5: LOWEST
6: ASM: class harmonised.pmmo.events.EventHandler onDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "java.util.Map.get(Object)" is null
at TRANSFORMER/pmmo@1.3.21/harmonised.pmmo.core.perks.FeaturePerks.saveAttributesOnDeath(FeaturePerks.java:96)
at TRANSFORMER/pmmo@1.3.21/harmonised.pmmo.core.perks.__FeaturePerks_saveAttributesOnDeath_LivingDeathEvent.invoke(.dynamic)
at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
at TRANSFORMER/forge@47.2.30/net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:303)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_6667_(ServerPlayer.java:573)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1182)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_6469_(Player.java:840)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_6469_(ServerPlayer.java:695)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_6074_(LivingEntity.java:261)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.commands.KillCommand.m_137813_(KillCommand.java:32)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.commands.KillCommand.m_137809_(KillCommand.java:25)
at MC-BOOTSTRAP/brigadier@1.1.8/com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.commands.Commands.m_242674_(Commands.java:257)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_246958_(ServerGamePacketListenerImpl.java:1246)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_244885_(ServerGamePacketListenerImpl.java:1223)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:67)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.TickTask.run(TickTask.java:18)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
at java.base/java.lang.Thread.run(Thread.java:833)

[00:14:12] [Render thread/INFO]: [System] [CHAT] An unexpected error occurred trying to execute that command
```

So idk what is it, but i just used /kill and the message *An unexpected error occurred trying to execute that command* appears  in the chat

**Comment by Shadowyjp** [comment]
idk what happened, but it stopped on its own.
