### ISSUE TITLE
if u close the smith table game crashing

### ISSUE THREAD

**Issue by Aprenax** [Caltinor/Project-MMO-2.0#547]
at TRANSFORMER/minecraft@1.21/com.mojang.blaze3d.vertex.BufferBuilder.buildOrThrow(BufferBuilder.java:69) ~[client-1.21-20240613.152323-srg.jar%23187!/:?] {re:classloading}
	at TRANSFORMER/pmmo@2.3.4/harmonised.pmmo.client.gui.TutorialOverlayGUI.render(TutorialOverlayGUI.java:102) ~[pmmo-1.21-2.3.4.jar%23192!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.0.8-beta/net.neoforged.neoforge.client.gui.GuiLayerManager.renderInner(GuiLayerManager.java:69) ~[neoforge-21.0.8-beta-universal.jar%23188!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.0.8-beta/net.neoforged.neoforge.client.gui.GuiLayerManager.render(GuiLayerManager.java:59) ~[neoforge-21.0.8-beta-universal.jar%23188!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.gui.Gui.render(Gui.java:234) ~[client-1.21-20240613.152323-srg.jar%23187!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}

**Comment by Caltinor** [comment]
@Aprenax it might take a minute or so on Modrinth/Curseforge for the file to appear, but there's now an updated version that fixes this.
