### ISSUE TITLE
recipe book crash 

### ISSUE THREAD

**Issue by Aprenax** [Caltinor/Project-MMO-2.0#548]
i found again crash sorry :(

at TRANSFORMER/pmmo@2.3.5/harmonised.pmmo.features.autovalues.AutoValueConfig$WearableTypes.fromSlot(AutoValueConfig.java:215) ~[pmmo-1.21-2.3.5.jar%23192!/:?] {re:classloading,pl:runtime_enum_extender:A}
	at TRANSFORMER/pmmo@2.3.5/harmonised.pmmo.features.autovalues.AutoItem.getWearableData(AutoItem.java:243) ~[pmmo-1.21-2.3.5.jar%23192!/:?] {re:classloading}
	at TRANSFORMER/pmmo@2.3.5/harmonised.pmmo.features.autovalues.AutoItem.processXpGains(AutoItem.java:165) ~[pmmo-1.21-2.3.5.jar%23192!/:?] {re:classloading}
	at TRANSFORMER/pmmo@2.3.5/harmonised.pmmo.features.autovalues.AutoValues.getExperienceAward(AutoValues.java:74) ~[pmmo-1.21-2.3.5.jar%23192!/:?] {re:classloading}
	at TRANSFORMER/pmmo@2.3.5/harmonised.pmmo.core.Core.getCommonXpAwardData(Core.java:216) ~[pmmo-1.21-2.3.5.jar%23192!/:?] {re:classloading}
	at TRANSFORMER/pmmo@2.3.5/harmonised.pmmo.core.Core.getExperienceAwards(Core.java:170) ~[pmmo-1.21-2.3.5.jar%23192!/:?] {re:classloading}
	at TRANSFORMER/pmmo@2.3.5/harmonised.pmmo.client.events.TooltipHandler.getXpData(TooltipHandler.java:124) ~[pmmo-1.21-2.3.5.jar%23192!/:?] {re:classloading}
	at TRANSFORMER/pmmo@2.3.5/harmonised.pmmo.client.events.TooltipHandler.lambda$onTooltip$5(TooltipHandler.java:71) ~[pmmo-1.21-2.3.5.jar%23192!/:?] {re:classloading}
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?] {}
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?] {}
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?] {}
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at TRANSFORMER/pmmo@2.3.5/harmonised.pmmo.client.events.TooltipHandler.onTooltip(TooltipHandler.java:73) ~[pmmo-1.21-2.3.5.jar%23192!/:?] {re:classloading}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.1.jar%23107!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.1.jar%23107!/:?] {}
	at TRANSFORMER/neoforge@21.0.8-beta/net.neoforged.neoforge.event.EventHooks.onItemTooltip(EventHooks.java:437) ~[neoforge-21.0.8-beta-universal.jar%23188!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.item.ItemStack.getTooltipLines(ItemStack.java:813) ~[client-1.21-20240613.152323-srg.jar%23187!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.gui.screens.Screen.getTooltipFromItem(Screen.java:243) ~[client-1.21-20240613.152323-srg.jar%23187!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.gui.screens.recipebook.RecipeButton.getTooltipText(RecipeButton.java:135) ~[client-1.21-20240613.152323-srg.jar%23187!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.gui.screens.recipebook.RecipeBookPage.renderTooltip(RecipeBookPage.java:140) ~[client-1.21-20240613.152323-srg.jar%23187!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.gui.screens.recipebook.RecipeBookComponent.renderTooltip(RecipeBookComponent.java:278) ~[client-1.21-20240613.152323-srg.jar%23187!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.gui.screens.inventory.CraftingScreen.render(CraftingScreen.java:63) ~[client-1.21-20240613.152323-srg.jar%23187!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.gui.screens.Screen.renderWithTooltip(Screen.java:112) ~[client-1.21-20240613.152323-srg.jar%23187!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/neoforge@21.0.8-beta/net.neoforged.neoforge.client.ClientHooks.drawScreenInternal(ClientHooks.java:406) ~[neoforge-21.0.8-beta-universal.jar%23188!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.0.8-beta/net.neoforged.neoforge.client.ClientHooks.drawScreen(ClientHooks.java:400) ~[neoforge-21.0.8-beta-universal.jar%23188!/:?] {re:classloading}

**Comment by Caltinor** [comment]
the top part of that crash is cut off.
