### ISSUE TITLE
NoClassDefFoundError: net/neoforged/testframework/conf/FrameworkConfiguration

### ISSUE THREAD

**Issue by neohyuga** [Caltinor/Project-MMO-2.0#567]
Minecraft Server 1.21 fails to start when PMMO mod version 2.3.8 is loaded.

Using neoforge-21.0.55-beta

Exception is:

[05Jul2024 01:35:14.059] [main/FATAL] [net.neoforged.fml.ModLoader/LOADING]: Failed to wait for future Mod Construction, 1 errors found
[05Jul2024 01:35:14.225] [main/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID 3f8bda7a-0316-435a-9438-8d6addaacae4
[05Jul2024 01:35:14.225] [main/FATAL] [net.neoforged.neoforge.server.loading.ServerModLoader/]: Crash report saved to ./crash-reports/crash-2024-07-05_01.35.14-fml.txt
[05Jul2024 01:35:14.226] [main/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID 5fb173de-4c7f-448f-8b6e-b27a517892ef
[05Jul2024 01:35:14.226] [main/ERROR] [net.minecraft.server.Main/FATAL]: Failed to start the minecraft server
net.neoforged.fml.ModLoadingException: Loading errors encountered:
        - Project MMO (pmmo) has failed to load correctly
          java.lang.NoClassDefFoundError: net/neoforged/testframework/conf/FrameworkConfiguration

        at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.ModLoader.waitForFuture(ModLoader.java:280) ~[loader-4.0.6.jar%2360!/:4.0]
        at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.ModLoader.dispatchParallelTask(ModLoader.java:243) ~[loader-4.0.6.jar%2360!/:4.0]
        at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.ModLoader.constructMods(ModLoader.java:151) ~[loader-4.0.6.jar%2360!/:4.0]
        at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:141) ~[loader-4.0.6.jar%2360!/:4.0]
        at TRANSFORMER/neoforge@21.0.55-beta/net.neoforged.neoforge.internal.CommonModLoader.begin(CommonModLoader.java:47) ~[neoforge-21.0.55-beta-universal.jar%23149!/:?]
        at TRANSFORMER/neoforge@21.0.55-beta/net.neoforged.neoforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[neoforge-21.0.55-beta-universal.jar%23149!/:?]
        at TRANSFORMER/minecraft@1.21/net.minecraft.server.Main.main(Main.java:124) ~[server-1.21-20240613.152323-srg.jar%23148!/:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.6.jar%2360!/:4.0]
        at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:128) ~[loader-4.0.6.jar%2360!/:4.0]
        at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:32) ~[loader-4.0.6.jar%2360!/:4.0]
        at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.6.jar%2360!/:4.0]
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.3.jar%2362!/:?]
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.3.jar%2362!/:?]
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.3.jar%2362!/:?]
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.3.jar%2362!/:?]
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.3.jar%2362!/:?]
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.3.jar%2362!/:?]
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.3.jar%2362!/:?]
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?]
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?]

**Comment by Caltinor** [comment]
new build currently processing and will be uploaded thereafter

**Comment by neohyuga** [comment]
I was able to get the mod and server to load with 2.3. Thank you for the quick fix!
